# All the files we depend on. We are using a negative pattern to not include anything by accident.
# node_modules, packages (contains git submodules and node modules etc.), devnet dirs etc. all add up a lot.
*

!/cannon
!/inura-batcher
!/inura-bindings
!/inura-bootnode
!/inura-chain-ops
!/inura-challenger
!/inura-heartbeat
!/inura-node
!/inura-preimage
!/inura-program
!/inura-proposer
!/inura-service
!/inura-wheel
!/go.mod
!/go.sum
