FROM golang:1.20.4-alpine3.16 as builder

RUN apk add --no-cache make gcc musl-dev linux-headers git jq bash

COPY ./go.mod /app/go.mod
COPY ./go.sum /app/go.sum

COPY ./inura-bindings /app/inura-bindings
COPY ./inura-service /app/inura-service

WORKDIR /app/inura-node
RUN go mod download -x

COPY ./inura-node /app/inura-node

RUN go build -o ./bin/stateviz ./cmd/stateviz

FROM alpine:3.16

COPY --from=builder /app/inura-node/bin/stateviz /usr/local/bin

CMD ["stateviz"]
